### ISSUE TITLE
alpha-premultiplied vs non-alpha-premultiplied

### ISSUE THREAD

**Issue by nigeltao** [mehlon/farbfeld#18]
I believe that the farbfeld format is non-alpha-premultiplied, like PNG and WebP lossless (VP8L).

Go's image.RGBA64 is alpha-premultiplied. You should be using image.NRGBA64 with an 'N' instead.

Also, the Color.RGBA method returns alpha-premultiplied values, so you'll have to un-premultiply when you encode.

**Comment by FRIGN** [comment]
Just for completeness, I added a note in farbfeld(5) regarding alpha-premultiplication (and on the website):
http://git.suckless.org/farbfeld/tree/farbfeld.5
